w           cycle sub-visibility
UP          cycle sub-visibility
s           no-osd sub-seek 0
DOWN        no-osd sub-seek 0
a           no-osd sub-seek -1
LEFT        no-osd sub-seek -1
d           no-osd sub-seek 1
RIGHT       no-osd sub-seek 1

Ctrl+LEFT   seek -5
Ctrl+RIGHT  seek 5

ESC         quit
q           script-message @migaku export
e           script-message @migaku lookup

Ctrl+z      set sub-delay 0.0

k           cycle secondary-sid
K           cycle secondary-sid down
W           no-osd cycle secondary-sub-visibility

Ctrl+s      screenshot
Ctrl+S      screenshot video


# === Chapters ===
PGUP  add chapter -1
PGDWN add chapter +1

# === Misc ===
q quit

# === Subs ===
x add sub-delay -0.1
X add sub-delay +0.1
v add sub-scale -0.05
V add sub-scale +0.05

